// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorktreeMenu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWorktreeMenuPackageString = "3fc104f8-7302-4948-8993-af1af5a61e5d";
        public static Guid guidWorktreeMenuPackage = new Guid(guidWorktreeMenuPackageString);

        public const string guidWorktreeMenuPackageCmdSetString = "256e5347-7680-497b-a9f3-74b15dc81a42";
        public static Guid guidWorktreeMenuPackageCmdSet = new Guid(guidWorktreeMenuPackageCmdSetString);

        public const string guidImagesString = "77fd0004-1362-49fc-8641-962ebddac99d";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidWorktreeMenuPackageCmdSet1String = "79b4d408-7f8c-4fe8-a0f5-2486657dc6cd";
        public static Guid guidWorktreeMenuPackageCmdSet1 = new Guid(guidWorktreeMenuPackageCmdSet1String);

        public const string guidImages1String = "89f671a4-8ab0-497c-9c4a-0c8481d3e337";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int cmdidMRUList = 0x0200;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int cmdidcmdidMRUList = 0x0100;
    }
}