// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TopLevelMenu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTopLevelMenuPackageString = "e41dd5d0-899a-4994-84f9-ebd689bcb422";
        public static Guid guidTopLevelMenuPackage = new Guid(guidTopLevelMenuPackageString);

        public const string guidTopLevelMenuPackageCmdSetString = "23495837-b876-4111-9ade-31c77e59af5b";
        public static Guid guidTopLevelMenuPackageCmdSet = new Guid(guidTopLevelMenuPackageCmdSetString);

        public const string guidGitLogoString = "424a70f0-0912-4aea-8fac-ceb175d08e39";
        public static Guid guidGitLogo = new Guid(guidGitLogoString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenu = 0x1021;
        public const int cmdidTestSubCommand = 0x0105;
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int MRUListGroup = 0x1200;
        public const int cmdidMRUList = 0x0200;
        public const int bmpGit = 0x0001;
    }
}