// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionsToolbar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSolutionsToolbarPackageString = "245ab73f-48b5-4ca1-ba40-22e2434034df";
        public static Guid guidSolutionsToolbarPackage = new Guid(guidSolutionsToolbarPackageString);

        public const string guidSolutionsToolbarPackageCmdSetString = "7c5421ef-54d3-4f13-b043-5bd988794dfc";
        public static Guid guidSolutionsToolbarPackageCmdSet = new Guid(guidSolutionsToolbarPackageCmdSetString);

        public const string guidImagesString = "14c3d29b-d40a-407d-aed6-ea0e862d0c83";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SolutionsToolBarCommandId = 0x0100;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}