// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionsToolbar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSolutionsToolbarPackageString = "245ab73f-48b5-4ca1-ba40-22e2434034df";
        public static Guid guidSolutionsToolbarPackage = new Guid(guidSolutionsToolbarPackageString);

        public const string guidSolutionsToolbarPackageCmdSetString = "7c5421ef-54d3-4f13-b043-5bd988794dfc";
        public static Guid guidSolutionsToolbarPackageCmdSet = new Guid(guidSolutionsToolbarPackageCmdSetString);

        public const string guidImages2String = "48b3adf4-62e9-4c75-ae2f-3002c82c48d9";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "12e3c3aa-058c-40c6-bbe2-53f879ff9137";
        public static Guid guidImages3 = new Guid(guidImages3String);

        public const string guidImages4String = "0b0eaaaa-4baa-4c84-802d-af4e86aa0699";
        public static Guid guidImages4 = new Guid(guidImages4String);

        public const string guidImages5String = "4b179669-6c49-4ef5-9df0-cc2421977263";
        public static Guid guidImages5 = new Guid(guidImages5String);

        public const string guidImagesString = "d6474e30-29b5-4a5f-a66b-701f1cc0dd81";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages6String = "52edc332-c4e8-42d0-a4e3-27fb3e6b0bf4";
        public static Guid guidImages6 = new Guid(guidImages6String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FrameworkToolBarComboId = 0x0100;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int FrameworkCommandList = 0x0111;
        public const int cmdidCommand1 = 0x1051;
        public const int cmdidRunSolutionCommand = 0x1052;
        public const int cmdidBuildSolutionCommand = 0x1053;
        public const int cmdidRebuildSolutionCommand = 0x1054;
        public const int cmdidPublishSolutionCommand = 0x1055;
        public const int cmdidSolutionFileSelectCommand = 0x1056;
        public const int cmdidSolutionFileListCommand = 0x1057;
        public const int pngRun = 0x0001;
        public const int pngBuild = 0x0001;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}